### ISSUE TITLE
Terraform provider docs are inconsistent about the JSON object view

### ISSUE THREAD

**Issue by strugee** [Flagsmith/flagsmith-docs#317]
One of the green "tip" messages at the top of the page says:

> Some API actions require object UUIDs/IDs to be referenced. You can enable the [JSON View](https://docs.flagsmith.com/clients/rest#json-view) from your account settings page which will help you access these variables.

But later down in the rest of the page, the instructions say "we're working on adding a JSON View, in the meantime you need to inspect the network requests". This is inconsistent with the green tip message and honestly, having to inspect the network requests isn't a great product experience so it's probably a good idea to get these outdated instructions removed.

gz#498

**Comment by dabeeeenster** [comment]
Thanks!
